### ISSUE TITLE
Moleculer JS compatibility

### ISSUE THREAD

**Issue by pentateu** [moleculer-go/moleculer#55]
@dehypnosis had the following issues while trying to integrate with Moleculer JS.

Current moleculer-go seems that has not exactly same protocol with moelculer-js. For example, moelculer-go discovers remote actions as []interfaces{} type assertion, but moleculer-js services reply as map[string]interfaces{}. And there are some issues while discovering, and call each others between different moleculer client library.

**Comment by pentateu** [comment]
@dehypnosis do you have a sample project that I can use to test and fix the issues between JS and Go services ? if not is fine, I just want to check before I start to avoid duplication of work.. in case u had one.

**Comment by dehypnosis** [comment]
@pentateu i made a PR!

**Comment by dehypnosis** [comment]
im sorry for i cannot provide moleculerjs thing for you. all of them are properties of the company and i quit the job few days ago.
but here is a molecuker-go project which has been made after i quit the job. and has no credential informations.

https://github.com/strix-kr/mol-weather/blob/master/service/weather/weather.service.go

but will be turned to private soon.

**Comment by pentateu** [comment]
merged on version v0.1.1

**Comment by dehypnosis** [comment]
Hey, thanks for your hard works.

I found `./version/version.go` has not been updated for new release.
And I have applied your new release, but found some networking problem.

With default configuration and NATS transporter, moleculer-go disconnect remote moleculer-js services right after discovery.

#### disconnection from moleculer-go
```
INFO[0000] Moleculer is starting...                      broker=imac.local-jrSGs
INFO[0000] Node ID: imac.local-jrSGs                     broker=imac.local-jrSGs
INFO[0000] Transporter: NatsTransporter                  Transit= broker=imac.local-jrSGs
INFO[0000] Connected to nats://dev.nats.svc.cluster.local:4222  Transit= broker=imac.local-jrSGs transport=nats
INFO[0000] Registry - remote $node service is registered.  broker=imac.local-jrSGs registry=imac.local-jrSGs
INFO[0000] Registry - remote pm service is registered.   broker=imac.local-jrSGs registry=imac.local-jrSGs
INFO[0000] Registry - remote pm.auth service is registered.  broker=imac.local-jrSGs registry=imac.local-jrSGs
INFO[0000] Registry - remote pm.user service is registered.  broker=imac.local-jrSGs registry=imac.local-jrSGs
INFO[0000] Registry - remote pm.kepco service is registered.  broker=imac.local-jrSGs registry=imac.local-jrSGs
INFO[0001] Registry - $node service is registered.       broker=imac.local-jrSGs registry=imac.local-jrSGs
INFO[0001] Registry - weather service is registered.     broker=imac.local-jrSGs registry=imac.local-jrSGs
INFO[0001] Service Broker with 2 service(s) started successfully.  broker=imac.local-jrSGs
INFO[0001] weather service has been stared               action=service.start broker=imac.local-jrSGs
INFO[0001] Registry - remote $node service is registered.  broker=imac.local-jrSGs registry=imac.local-jrSGs
INFO[0001] Registry - remote iam.admin service is registered.  broker=imac.local-jrSGs registry=imac.local-jrSGs
INFO[0001] Registry - remote iam service is registered.  broker=imac.local-jrSGs registry=imac.local-jrSGs
INFO[0001] Registry - remote iam.user service is registered.  broker=imac.local-jrSGs registry=imac.local-jrSGs
INFO[0001] Registry - remote $node service is registered.  broker=imac.local-jrSGs registry=imac.local-jrSGs
INFO[0001] Registry - remote weather service is registered.  broker=imac.local-jrSGs registry=imac.local-jrSGs
INFO[0001] Registry - remote $node service is registered.  broker=imac.local-jrSGs registry=imac.local-jrSGs
INFO[0001] Registry - remote hello service is registered.  broker=imac.local-jrSGs registry=imac.local-jrSGs
INFO[0001] Registry - remote $node service is registered.  broker=imac.local-jrSGs registry=imac.local-jrSGs
INFO[0001] Registry - remote trade.agencies service is registered.  broker=imac.local-jrSGs registry=imac.local-jrSGs
INFO[0001] Registry - remote trade.alarms service is registered.  broker=imac.local-jrSGs registry=imac.local-jrSGs
INFO[0001] Registry - remote trade.bids service is registered.  broker=imac.local-jrSGs registry=imac.local-jrSGs
INFO[0001] Registry - remote trade.brokers service is registered.  broker=imac.local-jrSGs registry=imac.local-jrSGs
INFO[0001] Registry - remote trade.efficiencies service is registered.  broker=imac.local-jrSGs registry=imac.local-jrSGs
INFO[0001] Registry - remote trade.forecasts service is registered.  broker=imac.local-jrSGs registry=imac.local-jrSGs
INFO[0001] Registry - remote trade.generations service is registered.  broker=imac.local-jrSGs registry=imac.local-jrSGs
INFO[0001] Registry - remote trade.generators service is registered.  broker=imac.local-jrSGs registry=imac.local-jrSGs
INFO[0001] Registry - remote trade.groups service is registered.  broker=imac.local-jrSGs registry=imac.local-jrSGs
INFO[0001] Registry - remote trade.plants service is registered.  broker=imac.local-jrSGs registry=imac.local-jrSGs
INFO[0001] Registry - remote trade service is registered.  broker=imac.local-jrSGs registry=imac.local-jrSGs
INFO[0002] Registry - remote $node service is registered.  broker=imac.local-jrSGs registry=imac.local-jrSGs
INFO[0002] Registry - remote api.graphql service is registered.  broker=imac.local-jrSGs registry=imac.local-jrSGs
INFO[0002] Registry - remote api.guard service is registered.  broker=imac.local-jrSGs registry=imac.local-jrSGs
INFO[0002] Registry - remote api.catalog service is registered.  broker=imac.local-jrSGs registry=imac.local-jrSGs
INFO[0002] Registry - remote api.document service is registered.  broker=imac.local-jrSGs registry=imac.local-jrSGs
INFO[0002] Registry - remote api.i18n service is registered.  broker=imac.local-jrSGs registry=imac.local-jrSGs
INFO[0002] Registry - remote api service is registered.  broker=imac.local-jrSGs registry=imac.local-jrSGs
INFO[0002] Registry - remote file service is registered.  broker=imac.local-jrSGs registry=imac.local-jrSGs
INFO[0002] Registry - remote $node service is registered.  broker=imac.local-jrSGs registry=imac.local-jrSGs
INFO[0002] Registry - remote $node service is registered.  broker=imac.local-jrSGs registry=imac.local-jrSGs

(omitted...)

INFO[0002] Registry - remote trade.groups service is registered.  broker=imac.local-jrSGs registry=imac.local-jrSGs
INFO[0002] Registry - remote trade.plants service is registered.  broker=imac.local-jrSGs registry=imac.local-jrSGs
INFO[0002] Registry - remote trade service is registered.  broker=imac.local-jrSGs registry=imac.local-jrSGs
WARN[0031] Node mol-weather-869cddb868-wrcbt-82677 disconnected   broker=imac.local-jrSGs registry=imac.local-jrSGs
WARN[0031] Node mol-template-ts-5f845f87b6-tnrf2-15 disconnected   broker=imac.local-jrSGs registry=imac.local-jrSGs
WARN[0031] Node peak-manager-api-56c6796f5c-89456-1 disconnected   broker=imac.local-jrSGs registry=imac.local-jrSGs
WARN[0031] Node cli-imac.local-90559 disconnected        broker=imac.local-jrSGs registry=imac.local-jrSGs
WARN[0031] Node eunjus-imac.local-46756 disconnected     broker=imac.local-jrSGs registry=imac.local-jrSGs
WARN[0031] Node eunjus-imac.local-46968 disconnected     broker=imac.local-jrSGs registry=imac.local-jrSGs
WARN[0031] Node mol-iam-75dffc6c45-876v6-21 disconnected   broker=imac.local-jrSGs registry=imac.local-jrSGs
WARN[0031] Node trade-sc-server-6b86d8ff-cf24d-21 disconnected   broker=imac.local-jrSGs registry=imac.local-jrSGs
WARN[0031] Node mol-api-5f885d4bc8-9zqph-21 disconnected   broker=imac.local-jrSGs registry=imac.local-jrSGs

```


Also I tried to call `moleculer-go` from `moleculer-js` (moleculer-cli REPL), but `moleculer-go` continues to be connected and disconnected repeatedly. I guess heartbeat is not working correctly.

#### moleculer-cli displays reconnecting moleculer-go logs
```
mol $ nodes
╔═════════════════════════════════════╤══════════╤═════════╤══════════════╤══════════════════════╤══════════╤════════════════════════════╗
║ Node ID                             │ Services │ Version │ Client       │ IP                   │    State │ CPU                        ║
╟─────────────────────────────────────┼──────────┼─────────┼──────────────┼──────────────────────┼──────────┼────────────────────────────╢
║ cli-imac.local-90559 (*)            │ 1        │  0.13.8 │ nodejs       │ 222.107.184.34  (+1) │  ONLINE  │ [....................] 2%  ║
║ eunjus-imac.local-46756             │ 8        │  0.13.7 │ nodejs       │ 192.168.2.214        │  ONLINE  │ [■■..................] 9%  ║
║ eunjus-imac.local-46968             │ 12       │  0.13.8 │ nodejs       │ 192.168.2.214        │  ONLINE  │ [■■..................] 11% ║
║ imac.local-jrSGs                    │ 2        │   0.1.0 │ moleculer-go │ 222.107.184.34  (+1) │  ONLINE  │ ?                          ║
║ mol-api-5f885d4bc8-9zqph-21         │ 8        │  0.13.7 │ nodejs       │ 10.20.7.99           │  ONLINE  │ [■...................] 5%  ║
║ mol-iam-75dffc6c45-876v6-21         │ 4        │  0.13.7 │ nodejs       │ 10.20.6.148          │  ONLINE  │ [■...................] 6%  ║
║ mol-template-ts-5f845f87b6-tnrf2-15 │ 2        │  0.13.8 │ nodejs       │ 10.20.2.92           │  ONLINE  │ [■■..................] 10% ║
║ mol-weather-869cddb868-wrcbt-82677  │ 2        │   0.1.0 │ moleculer-go │ 10.20.6.190          │  ONLINE  │ [....................] 0%  ║
║ peak-manager-api-56c6796f5c-89456-1 │ 5        │  0.13.8 │ nodejs       │ 10.20.0.2            │  ONLINE  │ [■■■.................] 14% ║
║ trade-sc-server-6b86d8ff-cf24d-21   │ 12       │  0.13.8 │ nodejs       │ 10.20.2.167          │  ONLINE  │ [■■■.................] 15% ║
╚═════════════════════════════════════╧══════════╧═════════╧══════════════╧══════════════════════╧══════════╧════════════════════════════╝

mol $ dcall imac.local-jrSGs $node.health
{ options: {},
  nodeID: 'imac.local-jrSGs',
  actionName: '$node.health' }
>> Call '$node.health' on imac.local-jrSGs with params: {}
[2019-05-07T11:33:47.202Z] WARN  cli-imac.local-90559/BROKER: Service '$node.health' is not found on 'imac.local-jrSGs' node.
>> ERROR: Service '$node.health' is not found on 'imac.local-jrSGs' node.
ServiceNotFoundError: Service '$node.health' is not found on 'imac.local-jrSGs' node.
    at ServiceBroker.findNextActionEndpoint (/usr/local/lib/node_modules/moleculer-cli/node_modules/moleculer/src/service-broker.js:840:13)
    at ServiceBroker.call (/usr/local/lib/node_modules/moleculer-cli/node_modules/moleculer/src/service-broker.js:876:25)
    at call (/usr/local/lib/node_modules/moleculer-cli/node_modules/moleculer-repl/src/commands/call.js:74:9)
    at CommandInstance.vorpal.command.option.option.option.allowUnknownOptions.action (/usr/local/lib/node_modules/moleculer-cli/node_modules/moleculer-repl/src/commands/call.js:138:27)
    at Session.session.execCommandSet (/usr/local/lib/node_modules/moleculer-cli/node_modules/vorpal/dist/session.js:470:20)
    at Vorpal.vorpal._exec (/usr/local/lib/node_modules/moleculer-cli/node_modules/vorpal/dist/vorpal.js:960:18)
    at Vorpal.vorpal._execQueueItem (/usr/local/lib/node_modules/moleculer-cli/node_modules/vorpal/dist/vorpal.js:751:17)
    at Vorpal.vorpal._queueHandler (/usr/local/lib/node_modules/moleculer-cli/node_modules/vorpal/dist/vorpal.js:735:10)
    at Vorpal.vorpal.exec (/usr/local/lib/node_modules/moleculer-cli/node_modules/vorpal/dist/vorpal.js:682:10)
    at /usr/local/lib/node_modules/moleculer-cli/node_modules/vorpal/dist/vorpal.js:625:10
    at module.exports.completed (/usr/local/lib/node_modules/moleculer-cli/node_modules/vorpal/dist/ui.js:220:13)
    at module.exports.PromptUI.onCompletion (/usr/local/lib/node_modules/moleculer-cli/node_modules/vorpal/node_modules/inquirer/lib/ui/prompt.js:57:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/lib/node_modules/moleculer-cli/node_modules/rx-lite/rx.lite.js:1550:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/moleculer-cli/node_modules/rx-lite/rx.lite.js:1489:14)
    at Subject.onCompleted (/usr/local/lib/node_modules/moleculer-cli/node_modules/rx-lite/rx.lite.js:5871:19)
    at Subject.tryCatcher (/usr/local/lib/node_modules/moleculer-cli/node_modules/rx-lite/rx.lite.js:63:31)
Data:  { action: '$node.health', nodeID: 'imac.local-jrSGs' }
mol $ [2019-05-07T11:33:51.146Z] WARN  cli-imac.local-90559/REGISTRY: Heartbeat is not received from 'imac.local-jrSGs' node.
[2019-05-07T11:33:51.147Z] WARN  cli-imac.local-90559/REGISTRY: Node 'imac.local-jrSGs' disconnected unexpectedly.
[2019-05-07T11:33:56.930Z] INFO  cli-imac.local-90559/REGISTRY: Node 'imac.local-jrSGs' reconnected.
[2019-05-07T11:34:21.151Z] WARN  cli-imac.local-90559/REGISTRY: Heartbeat is not received from 'imac.local-jrSGs' node.
[2019-05-07T11:34:21.151Z] WARN  cli-imac.local-90559/REGISTRY: Node 'imac.local-jrSGs' disconnected unexpectedly.
[2019-05-07T11:34:21.832Z] INFO  cli-imac.local-90559/REGISTRY: Node 'imac.local-jrSGs' reconnected.
[2019-05-07T11:34:51.153Z] WARN  cli-imac.local-90559/REGISTRY: Heartbeat is not received from 'imac.local-jrSGs' node.
[2019-05-07T11:34:51.154Z] WARN  cli-imac.local-90559/REGISTRY: Node 'imac.local-jrSGs' disconnected unexpectedly.
[2019-05-07T11:34:51.499Z] INFO  cli-imac.local-90559/REGISTRY: Node 'imac.local-jrSGs' reconnected.
[2019-05-07T11:35:21.157Z] WARN  cli-imac.local-90559/REGISTRY: Heartbeat is not received from 'imac.local-jrSGs' node.
[2019-05-07T11:35:21.157Z] WARN  cli-imac.local-90559/REGISTRY: Node 'imac.local-jrSGs' disconnected unexpectedly.
[2019-05-07T11:36:00.102Z] INFO  cli-imac.local-90559/REGISTRY: Node 'imac.local-jrSGs' reconnected.
[2019-05-07T11:36:36.165Z] WARN  cli-imac.local-90559/REGISTRY: Heartbeat is not received from 'imac.local-jrSGs' node.
[2019-05-07T11:36:36.165Z] WARN  cli-imac.local-90559/REGISTRY: Node 'imac.local-jrSGs' disconnected unexpectedly.
[2019-05-07T11:36:40.904Z] INFO  cli-imac.local-90559/REGISTRY: Node 'imac.local-jrSGs' reconnected.
[2019-05-07T11:37:06.171Z] WARN  cli-imac.local-90559/REGISTRY: Heartbeat is not received from 'imac.local-jrSGs' node.
[2019-05-07T11:37:06.172Z] WARN  cli-imac.local-90559/REGISTRY: Node 'imac.local-jrSGs' disconnected unexpectedly.
[2019-05-07T11:37:07.202Z] INFO  cli-imac.local-90559/REGISTRY: Node 'imac.local-jrSGs' reconnected.
[2019-05-07T11:37:36.175Z] WARN  cli-imac.local-90559/REGISTRY: Heartbeat is not received from 'imac.local-jrSGs' node.
[2019-05-07T11:37:36.175Z] WARN  cli-imac.local-90559/REGISTRY: Node 'imac.local-jrSGs' disconnected unexpectedly.
[2019-05-07T11:37:36.507Z] INFO  cli-imac.local-90559/REGISTRY: Node 'imac.local-jrSGs' reconnected.
...
```

I will drill down this issue soon for more helpful report for you.

**Comment by pentateu** [comment]
Hi @dehypnosis good to hear that you started testing on it.

Did you find any more about this issue that helps us understand what is happening? Have you played with the heartbeat parameters to see if you can adjust by configuration only?
 I'll create a test that leaves for a couple of hours to monitor stability it is.
